CartPole-v0:
  gamma: 0.99
  batch_size: 128
  hidden_size: 128
  hidden_size2: 128

  replay_size: 1.0e+4
  replay_size_start: 10000

  epsilon_decay: 5000
  epsilon_final: 0.01
  epsilon_start: 1.0

  learning_rate: 1.0e-3


  stopping_reward: 195
  max_frames: 2.0e+5

  save_path: saved_models

  target_net_sync: 1.0e+3
  tau: 0.005
  alpha_sync: false

  clip_gradient: false

CartPole-v1:
  gamma: 0.99
  batch_size: 128
  hidden_size: 128
  hidden_size2: 128

  replay_size: 1.0e+6
  replay_size_start: 5000

  epsilon_decay: 50000
  epsilon_final: 0.001
  epsilon_start: 0.250

  learning_rate: 5.0e-4

  target_net_sync: 1.0e+3

  stopping_reward: 475
  max_frames: 5.0e+5

  save_path: saved_models

  tau: 0.005
  alpha_sync: true

  clip_gradient: false

LunarLander-v3:
  gamma: 0.99
  batch_size: 128
  hidden_size: 256
  hidden_size2: 300

  replay_size: 1.0e+6
  replay_size_start: 5000

  epsilon_decay: 50000
  epsilon_final: 0.001
  epsilon_start: 1.0

  learning_rate: 1.0e-3

  target_net_sync: 1.0e+3
  alpha_sync: false
  tau: 0.005

  stopping_reward: 200
  max_frames: 1.0e+6

  save_path: saved_models

  clip_gradient: false

